try:
    from SCons.Script import Import  # type: ignore
except Exception:
    # SCons not available (IDE/static analysis). Provide a minimal stub
    # so editors can import the script without errors. At runtime under
    # PlatformIO/SCons the real Import will be used.
    def Import(name):
        globals()[name] = None
import os
import shutil
import re

# Import environment from SCons
Import("env")
env = env  # type: ignore

# --- paths resolved via SCons environment ---
build_dir = env.subst("$BUILD_DIR")
# For espressif32 platform, use the framework-arduino path dynamically
libs_dir = env.subst(
    "$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/sdk/esp32s3/include"
)

# --- files ---
source_file = "sdkconfig.t2can"
dest_build = os.path.join(build_dir, "sdkconfig.h")
dest_include = os.path.join(libs_dir, "sdkconfig.h")

if os.path.exists(source_file):
    with open(source_file, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.split("\n")

    header_lines: list[str] = []
    header_lines.append("#ifndef SDKCONFIG_H")
    header_lines.append("#define SDKCONFIG_H")
    header_lines.append("")
    header_lines.append("/* Automatically generated from sdkconfig.t2can */")
    header_lines.append("/* DO NOT EDIT THIS FILE */")
    header_lines.append("")

    for line in lines:
        original_line = line
        line = line.strip()

        if not line:
            continue

        if line.startswith("#") and not line.startswith("CONFIG_"):
            if any(
                keyword in line
                for keyword in (
                    "Automatically",
                    "Espressif",
                    "Project Configuration",
                )
            ):
                header_lines.append(f"/* {line[2:].strip()} */")
            continue

        if line.startswith("CONFIG_"):
            if line.endswith("=y"):
                config_name = line.split("=", 1)[0]
                header_lines.append(f"#define {config_name} 1")
            elif "is not set" in line:
                continue
            elif line.endswith("=n"):
                continue
            # Handle CONFIG_XXX="value"
            elif '="' in line:
                name, value = line.split('="', 1)
                val = value.rstrip('"')
                header_lines.append(f'#define {name} "{val}"')
            elif "=" in line:
                name, value = line.split("=", 1)
                header_lines.append(f"#define {name} {value.strip()}")
            else:
                # Standalone CONFIG_XXX (assume enabled)
                header_lines.append(f"#define {line} 1")

    header_lines.append("")
    header_lines.append("#endif /* SDKCONFIG_H */")

    header_content = "\n".join(header_lines)

    os.makedirs(os.path.dirname(dest_build), exist_ok=True)
    with open(dest_build, "w", encoding="utf-8") as f:
        f.write(header_content)

    print(f"Generated sdkconfig.h -> {dest_build}")

    try:
        os.makedirs(os.path.dirname(dest_include), exist_ok=True)
        with open(dest_include, "w", encoding="utf-8") as f:
            f.write(header_content)
        print(f"Generated sdkconfig.h -> {dest_include}")
    except Exception as exc:
        print(
            f"Warning: could not write sdkconfig.h to include dir: {exc}"
        )
else:
    print(f"Error: source file not found: {source_file}")
