Import("env")
import os
import shutil
import re

# Get paths
build_dir = env.subst("$BUILD_DIR")
libs_dir = env.subst("$PROJECT_PACKAGES_DIR/framework-arduinoespressif32-libs/esp32s3/include")

# Source file
source_file = "sdkconfig.t2can"
dest_build = os.path.join(build_dir, "sdkconfig.h")
dest_include = os.path.join(libs_dir, "sdkconfig.h")

if os.path.exists(source_file):
    # Read source file
    with open(source_file, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Convert ESP-IDF config format to C header format
    lines = content.split('\n')
    header_lines = []
    header_lines.append("#ifndef SDKCONFIG_H")
    header_lines.append("#define SDKCONFIG_H")
    header_lines.append("")
    header_lines.append("/* Automatically generated from sdkconfig.t2can */")
    header_lines.append("/* DO NOT EDIT THIS FILE */")
    header_lines.append("")
    
    for line in lines:
        original_line = line
        line = line.strip()
        
        # Skip empty lines
        if not line:
            continue
        
        # Skip section headers and comments (lines starting with # that are not CONFIG_)
        if line.startswith('#') and not line.startswith('CONFIG_'):
            # Only keep important header comments, skip section markers
            if any(keyword in line for keyword in ['Automatically', 'Espressif', 'Project Configuration']):
                header_lines.append(f"/* {line[2:].strip()} */")
            continue
        
        # Process CONFIG_ lines
        if line.startswith('CONFIG_'):
            # Handle CONFIG_XXX=y
            if line.endswith('=y'):
                config_name = line.split('=')[0]
                header_lines.append(f"#define {config_name} 1")
            # Handle CONFIG_XXX is not set (skip these - they're undefined)
            elif 'is not set' in line:
                continue
            # Handle CONFIG_XXX=n (skip - means not set)
            elif line.endswith('=n'):
                continue
            # Handle CONFIG_XXX="value"
            elif '="' in line:
                parts = line.split('="', 1)
                config_name = parts[0]
                value = parts[1].rstrip('"')
                header_lines.append(f'#define {config_name} "{value}"')
            # Handle CONFIG_XXX=value (numeric or hex)
            elif '=' in line:
                parts = line.split('=', 1)
                config_name = parts[0]
                value = parts[1].strip()
                header_lines.append(f"#define {config_name} {value}")
            else:
                # Standalone CONFIG_XXX (assume enabled)
                header_lines.append(f"#define {line} 1")
    
    header_lines.append("")
    header_lines.append("#endif // SDKCONFIG_H")
    
    header_content = '\n'.join(header_lines)
    
    # Write to build directory
    os.makedirs(os.path.dirname(dest_build), exist_ok=True)
    with open(dest_build, 'w', encoding='utf-8') as f:
        f.write(header_content)
    print(f"Generated sdkconfig.h from {source_file} to {dest_build}")
    
    # Write to include directory (where framework headers look for it)
    include_dir = os.path.dirname(dest_include)
    try:
        os.makedirs(include_dir, exist_ok=True)
        with open(dest_include, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"Generated sdkconfig.h from {source_file} to {dest_include}")
    except Exception as e:
        print(f"Warning: Could not write to include directory {include_dir}: {e}")
else:
    print(f"Error: {source_file} not found!")
